language: c

script: asdf plugin-test sonarscanner $TRAVIS_BUILD_DIR "sonar-scanner -v"

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - jq

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew install jq; fi
